In [315]:
clima=['Ensolarado','Ensolarado','Nublado','Chuvoso','Chuvoso', 'Chuvoso', 'Nublado','Ensolarado', 'Ensolarado','Chuvoso', 'Ensolarado', 'Nublado','Nublado', 'Chuvoso']

temp=['Quente', 'Quente', 'Quente', 'Suave', 'Legal', 'Legal', 'Legal', 'Suave','Legal', 'Suave','Suave','Suave','Quente', 'Suave']

brincar = ['Não','Não','Sim','Sim','Sim','Não','Sim','Não','Sim','Sim','Sim','Sim','Sim','Não']

print(len(clima))
print(len(temp))
print(len(brincar))

14
14
14


In [316]:

import numpy as np

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

In [317]:
clima_encoded = le.fit_transform(clima)
temp_encoded = le.fit_transform(temp)
print(clima_encoded)
print(temp_encoded)

[1 1 2 0 0 0 2 1 1 0 1 2 2 0]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [318]:
alvo = le.fit_transform(brincar)
alvo

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [319]:
carac = list(zip(clima_encoded,temp_encoded))
carac

[(1, 1),
 (1, 1),
 (2, 1),
 (0, 2),
 (0, 0),
 (0, 0),
 (2, 0),
 (1, 2),
 (1, 0),
 (0, 2),
 (1, 2),
 (2, 2),
 (2, 1),
 (0, 2)]

In [320]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [321]:
modelo = GaussianNB()

In [322]:
modelo.fit(carac, alvo)

GaussianNB()

In [323]:
predito = modelo.predict([[2,2]])
predito

array([1])

In [324]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [325]:
iris = load_iris()

In [326]:
X = iris.data
y = iris.target

In [327]:
(X_train, X_test, y_train, y_test) = train_test_split(X, y)

In [328]:
modelo1 = GaussianNB()

modelo1.fit(X_train, y_train)

precisao1 = str(round(modelo1.score(X_test, y_test) * 100, 2))

print( "A Acurácia do modelo 1 foi", precisao1)


A Acurácia do modelo 1 foi 97.37


In [329]:
modelo2 = MultinomialNB()
modelo2.fit(X_train, y_train)
precisao2 = str(round(modelo2.score(X_test, y_test) * 100, 2))
print( "A Acurácia do modelo 2 foi", precisao2)


A Acurácia do modelo 2 foi 94.74


In [330]:
modelo3 = BernoulliNB()
modelo3.fit(X_train, y_train)
precisao3 = str(round(modelo3.score(X_test, y_test) * 100, 2))
print( "A Acurácia do modelo 3 foi", precisao3)

A Acurácia do modelo 3 foi 31.58


In [331]:
from sklearn.datasets import load_wine
import warnings

In [332]:
warnings.filterwarnings("ignore")

In [333]:
vinho = load_wine()

In [334]:
X = vinho.data
y = vinho.target

In [335]:
(X_train, X_test, y_train, y_test) = train_test_split(X, y)

In [336]:
from sklearn.neighbors import KNeighborsClassifier
modelo1 = KNeighborsClassifier()

modelo1.fit(X_train, y_train)

precisao1 = str(round(modelo1.score(X_test, y_test) * 100, 2))

print( "A Acurácia do modelo 1 foi", precisao1)

A Acurácia do modelo 1 foi 68.89


In [337]:
y_pred = modelo1.predict(X_test)

In [338]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.88      0.94      0.91        16
           1       0.73      0.47      0.57        17
           2       0.47      0.67      0.55        12

    accuracy                           0.69        45
   macro avg       0.69      0.69      0.68        45
weighted avg       0.71      0.69      0.69        45



In [339]:
modelo2 = GaussianNB()

modelo2.fit(X_train, y_train)

y_pred = modelo2.predict(X_test)

precisao2 = str(round(modelo2.score(X_test, y_test) * 100, 2))

print( "A Acurácia do modelo 2 foi", precisao2)


A Acurácia do modelo 2 foi 95.56


In [340]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.88      0.94        17
           2       0.86      1.00      0.92        12

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



In [341]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer()
scaler.fit(X)
X = scaler.transform(X)

In [342]:
scoresKNN=[]
scoresNB=[]

for i in range(2000):
    X_train, X_test, y_train, y_test = train_test_split(X, y)
    modelo1 = KNeighborsClassifier()

    modelo1.fit(X_train, y_train)

    precisao1 = str(round(modelo1.score(X_test, y_test) * 100, 2))

    scoresKNN.append(precisao1)
    modelo2 = GaussianNB()

    modelo2.fit(X_train, y_train)

    y_pred = modelo2.predict(X_test)

    precisao2 = str(round(modelo2.score(X_test, y_test) * 100, 2))
    scoresNB.append(precisao2)
    

In [344]:
print("Média do KNN: {:.2f}%".format(np.mean(scoresKNN)*100))
print("Desvio padrão do KNN: {:.2f}%".format(np.std(scoresKNN)*100))

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('<U5')) -> None

In [ ]:
print("Média do Naive Bayes: {:.2f}%".format(np.mean(scoresNB)*100))
print("Desvio padrão do Naive Bayes: {:.2f}%".format(np.std(scoresNB)*100))

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sns.displot(scoresKNN)